name: Go

on:
  push:
    branches: [ test ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get Go version from go.mod
      run: |
        go_version=$(cat go.mod | grep "^go" | cut -d ' ' -f 2)
        echo "go_version=${go_version}" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.go_version }}

    - name: Fmt
      run: go fmt ./...

    - name: Vet
      run: go vet ./...

    - name: Install Ginkgo
      run: go install github.com/onsi/ginkgo/v2/ginkgo

    - name: Test
      run: ginkgo --keep-going --trace -r --fail-on-pending --randomize-all --nodes=7 --race --timeout 20m ./...
